experimental_name: demo_toy_1 
device: cpu

# model hyperparameters
alpha: 1
beta: 10
limit_dim: 2500
model_type: varmsgplvm
learn_alpha: 0
learn_beta: 0
learn_inducing: 0
learn_kern: 0
learn_phi: 0
fix_var_par: 1 
KLweight: 0.5

optimise_alpha: 1
alpha_transform: exp
optimise_beta: 1
beta_transform: exp

# model.Q : the latent dimensions of the latent varible x.
# model.L : the number of the GP base components.
# model.M : the number of inducing points.
# model.D : the dimension of the output.
# model.N : the number of the instance.
Q: 8
D: 30
L: 3
M: 50
N: 100 





# before ----------------
# lr: 1e-2
# max_iter: 1000
# latent_dim_x: 1
# J: 1
# dynamic_kernel: "rbf_plus"
# base_kernel: "linard2_plus"

# inducing_points: 100
# jitter: 1e-5
# noise: 1e-5
